"""empty message

Revision ID: eed0b41e1d1b
Revises: 
Create Date: 2024-04-05 11:01:44.914951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eed0b41e1d1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=83), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('poster', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(),nullable=True)
    )
    # ### end Alembic commands ###
